server:
  port: 8001
spring:
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/study?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave_1:
          url: jdbc:mysql://localhost:3306/study_slave?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.guojia.resttemplatedemo.demos.entity
